osx_image: xcode10.2
language: objective-c
xcode_project: MultiPeer.xcodeproj

branches:
  only:
    master

before_install:
  - git clone https://github.com/dingwilson/devops-ci.git

script:
  - set -o pipefail

  - swift build -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.11"

  - pod spec lint

  - bundle exec danger --fail-on-errors=true

after_success:
  - source ./devops-ci/gen_jazzy_docs.sh
